### ISSUE TITLE
这个项目可以做PA 任务吗？

### ISSUE THREAD

**Issue by zuowanbushiwo** [alexw914/ASVspoof_CM#1]
你好
     可以使用你的工程训练一个可以同时检测PA,LA和DF的模型吗？我看了几篇文章和项目都是分开训练的，是因为这几个任务所需要的特征不一样吗？问题比较小白，我是刚入门ASVspoof，前段时间刚训练一个声纹的模型，昨天才开始看antispoof，ASVspoof的资料。谢谢！

**Comment by alexw914** [comment]
单个模型不能同时检测PA和LA，检测使用的特征不同，我没有做过PA，如果你要在这个工程下做PA你需要修改preprocess生成PA训练集和测试集的csv文件。同时需要修改测试EER和min-tDCF的函数，但是只能检测单独PA，LA可能没效果。
PA使用的特征以及设置和LA也不一样，你可以看ASVspoof2021总结论文https://arxiv.org/pdf/2210.02437.pdf。
另外工程是基于speechbrain的，你了解框架可能需要一定时间。

**Comment by zuowanbushiwo** [comment]
感谢回复
刚刚开始看anti-spoof 感觉是挺迷糊的，和比以前做AI任务概念要多一些。 我看这篇文章[REPLAY AND SYNTHETIC SPEECH DETECTION WITH RES2NET ARCHITECTURE](https://arxiv.org/abs/2010.15006)，好像使用相同的模型(res2net)和特征(CQT)能达到一个比较好的效果。

**Comment by alexw914** [comment]
可以的，你可以尝试一下，不过好像是得单独在两个数据集上分别训练PA和LA检测吧。这个特征比较难算，基本不能实时输入网络，需要离线计算，后来就没有使用。

**Comment by zuowanbushiwo** [comment]
>不过好像是得单独在两个数据集上分别训练PA和LA检测吧

是的，不过我不知道原因，我理解应该是可以合并的，特征，模型和损失函数都一样，应该是可以合并了，只是合并最后的类别多一点。 可能分开做好对比一些，毕竟官方是分两个任务做的。可能商业的系统有做这样合并的。

>这个特征比较难算，基本不能实时输入网络，需要离线计算，后来就没有使用

非常感谢告知，我现在正按你的ReadMe下载数据。ASVspoof2021 的数据放到 zenodo上了的，国内访问好像比较慢，2019的PA和LA 数据都下载完成了。

感谢！

**Comment by alexw914** [comment]
不一定可行，这个特征关注的区域不一样，而且特征分布可能重合，你用一个模型检测两个可能两个精度都降低了。实现两个都检测只需要简单利用各自的score来做cascade就可以。

**Comment by zuowanbushiwo** [comment]
嗯，好的，有点理解了。可能和我们以前做的语音降噪功能有比较大的不一样，降噪基本都可以用同一个模型去做，只要训练的时候见过，不会区分各种不同的噪声。

看了你ReadMe 的Augment 数据扩增部分，不是很理解：
(1) LADF_aug 这个文件夹数据是什么时候产生的？ 从你training 部分的介绍看 `If you not prepare all work above, To train the model in ASVspoof2019 LA run  python train.py yaml/ecapa_2019.yaml `   是trian时 产生的吗，但是我看ecapa_2019.yaml 中augment 配置都被注释了，倒是ecapa_2021_LA.yaml 有augment  的配置参数？

(2) 表格中 Augment 那格的 transmission，compression 和 MUSAN+RIR 是什么意思？  transmission 是cm_dataset.py 的channel /codec 吗？同理compression 指 cm_dataset.py 中compression？  MUSAN+RIR是指 [SLR17](http://www.openslr.org/17/) 和 [SLR28](http://www.openslr.org/28/) 数据，我在代码中没看到加混响和噪声数据扩增？

**Comment by alexw914** [comment]
2019数据集不需要强化，没有编码的变化。你直接可以用2019LA来测试，大概EER1.86%左右。

2021数据集需要编码强化，LA需要编码转换强化（transmission），测试数据要过VoIP或PSTN，DF需要过压缩（compression）编码例如mp4,m4a等有损压缩编码。LA和DF强化策略也不同。需要先做好转码按我的格式放在文件夹里。这个方案用的是LFCC特征，用ECAPA训练的，模型在cm_2021_ecapa.py里面，这个强化方案我做了靠近60种编码。

你可以采用resnet18,不要加SE模块。使用MUSAN+RIR来进行数据强化，需要用Fbank特征，你直接用resnet的yaml文件设置就可以。强化方案写在了cm_2021.py中，这个效果反而做编码转换好，而且还能在线强化。

**Comment by zuowanbushiwo** [comment]
非常感谢您的回复
 LADF_aug 文件的wav 文件时 [ASVspoof2021_AIR](https://github.com/yzyouzhang/ASVspoof2021_AIR) 这个项目中的 channel_simulation 文件 python 文件产生的吗？
![image](https://user-images.githubusercontent.com/3354428/217497109-50a0b28f-ec35-4a28-a419-55a6b271b635.png)

**Comment by alexw914** [comment]
是的，还需要一个[开源项目](https://github.com/idiap/acoustic-simulator)，要根据他提供的来，那个开源项目要装好几个依赖库。还有问题需要可以q或者w189678990。

**Comment by zuowanbushiwo** [comment]
好的，真的非常感谢！
